global:
  scrape_interval:     15s # Default scrape interval

scrape_configs:
#  - job_name: 'prometheus' # Job to scrape Prometheus metrics
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['localhost:9090']

  - job_name: 'prometheus'
    metrics_path: '/metrics' # Job to scrape application metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.15.11:5000']